### PR TITLE
added test for finding empty string

### PR DESCRIPTION
**Pull request by jkotlinski**

### CODE REVIEW

**Comment by steverpalmer** [comment]
There are two possible intentions for this change:
 1. to exercise FIND on an empty word; (as indicated by the commit comment above)
 2. to exercise FIND on an word not in the dictionary. (as indicated by the removed comment in the file)

The proposed change does to exercise FIND on a non-existent word, and assumes that it will get a not-found (0) response.  If the empty word is not in the dictionary, then this will cover both the items listed above. However, I've checked the Forth standard and couldn't find anywhere which excludes the empty word from the dictionary.  Of course, it couldn't be defined with things like ":" or CONSTANT, but that doesn't mean that it couldn't be constructed.  Indeed, the Fig Forth model did construct unusual dictionary words, such as a single space word for vocabulary linkage and a NULL character word for the end-of-line processing.  So it is difficult to be certain that the empty word is not used somewhere by someone.

If the intention is item 1 (FIND on an empty word - a perfectly reasonable boundary-test), then I would suggest that the test must discard the return parameters as it can only test that the FIND application did not blow up.

If the intention is item 2, the I would suggest that an alternative non-existent word is selected.  In the exceptiontest.fth, it uses $$QWEQWEQWERT$$ as a word that is not expected to be in the dictionary.  Again, this is not defined by the Forth standard, but it would be very unlikely to occur in practice.  Also, the test-suite would be consistent in its assumptions.  In future, a non-existent word could be defined in a config file that has been proposed.

**Comment by jkotlinski** [comment]
Hi, my intention were to smack 1 and 2 both at the same time. I had no thought that "" could even be a valid word, since the standard specifies 1-31 chars. Is there even any legal way to create a word named "" ?

**Comment by jkotlinski** [comment]
I realize now it is probably quite valuable to split up the test in two sections, since the code paths taken are likely different. So I did just that! Thanks for the feedback!

**Comment by jkotlinski** [comment]
...then again, wouldn't it be quite worrying if a Forth FIND returned something else than 0 for empty string FIND? I think I would be quite happy to be alerted about that.

**Comment by jamesbowman** [comment]
Agreed: FIND with a 0-length string is a valid test case.


On Tue, Jan 12, 2016 at 11:01 AM, Johan Kotlinski <notifications@github.com>
wrote:

> ...then again, wouldn't it be quite worrying if a Forth FIND returned
> something else than 0 for empty string FIND? I think I would be quite happy
> to be alerted about that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gerryjackson/forth2012-test-suite/pull/15#issuecomment-171016363>
> .
>



-- 
James Bowman
http://www.excamera.com/

**Comment by gerryjackson** [comment]
I feel uncomfortable about assuming that a standard system will return (c-addr 0) from FIND for an empty string. There may be a good reason why someone has a header with a zero length string as a name even if it can't be generated in standard Forth. As it is a perfectly good test case we should include it. The question is what do we check, possibilities are:
- drop the returned values and check an empty stack
- check the TOS, if 0 check that caddr is returned else if +/-1 check that xt <> caddr
The second one covers all possibilities doesn't it, or is it over the top?

Regarding testing a name not in the dictionary, we can use the same name as in the exception test. Longer term, as Steve suggests, it should be specified in a configuration file, perhaps preceded by an undefined test.

**Comment by steverpalmer** [comment]
Johan - thanks for addressing my concern.  Thanks also for identifying the clause in section 3.3.1.2 on Definitions Names which, as you indicate specifies 1 ... 31 characters.  Unfortunately, the standard tends to specify what must be in the language as a minimum, rather than what the limits of the language.  For example, it defines words that must exist in a base system, but does not say that they are the only words that can exist.

I had another search myself to see if I could find anything else related to this question.  In particular, section 6.1.1550 on FIND includes a section on testing which states:

    HERE 3 C, CHAR G C, CHAR T C, CHAR 1 C, CONSTANT GT1STRING 
    HERE 3 C, CHAR G C, CHAR T C, CHAR 2 C, CONSTANT GT2STRING 
    T{ GT1STRING FIND -> ' GT1 -1 }T 
    T{ GT2STRING FIND -> ' GT2 1  }T 
    ( HOW TO SEARCH FOR NON-EXISTENT WORD? )

Looks familiar!!

I could find no other corroborating statement that find on the empty string will return 0.  On the other hand, I agree that it is an interesting question and I believe that the function of a test suite need not be limited to standards compliance.  However, the very first lines of the README.md file makes it clear that testing compliance is the first function of the test suite so I'd question whether a failure should be reported for something that it unexpected, but not necessarily non-compliant.  Therefore, I propose a compromise something like...

    HERE 0 C, CONSTANT EMPTYSTRING
    : EMPTYSTRING-FIND-CHECK ( c-addr 0 | xt 1 | xt -1 -- t|f )
        DUP IF ." FIND returns a TRUE value for an empty string!" CR THEN
        0= SWAP EMPTYSTRING = = ;
    T{ EMPTYSTRING FIND EMPTYSTRING-FIND-CHECK -> <TRUE> }T

This will:
 * exercise the FIND on an empty string as you've suggested
 * checks the results for standards compliance as suggested by Gerry
 * reports on what would be an unexpected result

**Comment by gerryjackson** [comment]
Yes Steve I think that does it. Can we put the test in coreplus.fth please. I have been reluctant to put additional tests into core.fr because of its copyright statement.

Are you going to add that test Johan  (and the not found test) or do you want me to do it?

Gerry

**Comment by jkotlinski** [comment]
@gerryjackson Since it already seems like you have a good idea what you want to do, and thought it through, I would be delighted if you did it :)

**Comment by gerryjackson** [comment]
OK will do - not tonight though, I've had a long day.

**Comment by gerryjackson** [comment]
I've added the FIND tests to coreplus.fth, many thanks Johan & Steve.

**Pull request closed without merging**
