### PR TITLE
fixes #1: Distinguishing no error tests from not run tests

### LINKED ISSUE #1: Error Reporting does not distinguish test not run and no errors found
After running the tests, a summary report is generated which lists the numbers of faults found for each test suite.  If no faults are found, then the summary line displays the test suite name and a "-".  This is fine, but is also used to present the results for a test suite that has not been run.  From a configuration management perspective, it would be better to display something different for those tests that have not been run.  Perhaps "n/a"?

### PR DESCRIPTION
**Pull request by steverpalmer**
I initialize the ERRORS[] array with -1, which get overwritten by run tests.  The SHOW-ERROR-LINE now reports "n/a" when it finds a -1 error count.  For example, the test results look like this:

    ---------------------------
            Error Report
    Word Set             Errors
    ---------------------------
    Core                    -
    Core extension         n/a
    Double number          n/a
    Exception               -
    Facility                -
    File-access             -
    Locals                 n/a
    Memory-allocation       1
    Programming-tools      n/a
    Search-order            -
    String                 n/a
    ---------------------------
    Total                   1
    ---------------------------

@gerryjackson - what do you think?

### CODE REVIEW

**Comment by gerryjackson** [comment]
That looks fine. A possible improvement could be to replace the '-' for no errors with a '0'. At first glance to me a '-' looks like not tested. This is easily done by omitting the second ELSE part in SHOW-ERROR-LINE. If you think it's worth it I'll leave you to do it and then we can accept the change.

**Comment by steverpalmer** [comment]
I'll change the "-" to be "0".  Given than change, and in-line with your first glance, I could also change the "n/a" to be "-".  (I quite like the "-" for not run, but this was already used for the 0-case.)

**Comment by steverpalmer** [comment]
The new output looks like:

    ---------------------------
            Error Report
    Word Set             Errors
    ---------------------------
    Core                    0
    Core extension          -
    Double number           -
    Exception               0
    Facility                0
    File-access             0
    Locals                  -
    Memory-allocation       1
    Programming-tools       -
    Search-order            0
    String                  -
    ---------------------------
    Total                   1
    ---------------------------

**Comment by gerryjackson** [comment]
Yes that's much better. Incidentally I've just sent you a longish email about things.

**Pull request merged**
